// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7wlR6nF_awb1NojHwiGudTBSQF4WdHU8',
    appId: '1:172131937774:web:6e8b2baa14b52cdb2eb2ff',
    messagingSenderId: '172131937774',
    projectId: 'fynxfit',
    authDomain: 'fynxfit.firebaseapp.com',
    databaseURL: 'https://fynxfit-default-rtdb.firebaseio.com',
    storageBucket: 'fynxfit.firebasestorage.app',
    measurementId: 'G-MMP6DQ7D7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyihQzGF_EYXSdky84x2k-_4Thnw4l440',
    appId: '1:172131937774:android:60b30e63f81b5f3f2eb2ff',
    messagingSenderId: '172131937774',
    projectId: 'fynxfit',
    databaseURL: 'https://fynxfit-default-rtdb.firebaseio.com',
    storageBucket: 'fynxfit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnYggzdQH4WnaQ5Dp_nFgCarg0SjtAMOs',
    appId: '1:172131937774:ios:b4256d7c89aedd4a2eb2ff',
    messagingSenderId: '172131937774',
    projectId: 'fynxfit',
    databaseURL: 'https://fynxfit-default-rtdb.firebaseio.com',
    storageBucket: 'fynxfit.firebasestorage.app',
    androidClientId: '172131937774-0q74f16ceg2mcqprvkf6h0bbfsuqmnnh.apps.googleusercontent.com',
    iosClientId: '172131937774-el7b5ecduntu91180o55c7t25sep8el6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fynxfitcoaches',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnYggzdQH4WnaQ5Dp_nFgCarg0SjtAMOs',
    appId: '1:172131937774:ios:b4256d7c89aedd4a2eb2ff',
    messagingSenderId: '172131937774',
    projectId: 'fynxfit',
    databaseURL: 'https://fynxfit-default-rtdb.firebaseio.com',
    storageBucket: 'fynxfit.firebasestorage.app',
    androidClientId: '172131937774-0q74f16ceg2mcqprvkf6h0bbfsuqmnnh.apps.googleusercontent.com',
    iosClientId: '172131937774-el7b5ecduntu91180o55c7t25sep8el6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fynxfitcoaches',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7wlR6nF_awb1NojHwiGudTBSQF4WdHU8',
    appId: '1:172131937774:web:2d07898c10dd21b72eb2ff',
    messagingSenderId: '172131937774',
    projectId: 'fynxfit',
    authDomain: 'fynxfit.firebaseapp.com',
    databaseURL: 'https://fynxfit-default-rtdb.firebaseio.com',
    storageBucket: 'fynxfit.firebasestorage.app',
    measurementId: 'G-JC8WRLZ568',
  );
}
